name: Drift Detection

on:
  push:
    branches: [master]
    paths:
      - '**/terraform/**'
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**/terraform/**'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  terraform-drift-test:
    name: "Test"
    uses: "Sopra-Steria-Code-Academy/Samling-1-Templates/.github/workflows/terraform-drift-template.yml@main"
    with:
      environment-name: 'terraform-plan'
    secrets:
      client-id: ${{ secrets.TF_AZURE_CLIENT_ID }}
      subscription-id: ${{ secrets.TF_AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.TF_AZURE_TENANT_ID }}
      client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
